// Golden index files (tests/data/golden, generated by the independent Python writer
// tools/make_golden.py). They must load in every mode with the expected contents and search
// results, and the C++ writer must reproduce them byte for byte.

#include <gtest/gtest.h>

#include <cmath>
#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <memory>
#include <span>
#include <string>
#include <vector>

#include <vectorforge/collection.hpp>
#include <vectorforge/simd.hpp>

#include "collection/collection_factory.hpp"
#include "index/hnsw/hnsw_backend.hpp"
#include "index/hnsw/hnsw_validator.hpp"
#include "support/brute_force_reference.hpp"
#include "support/persistence.hpp"

namespace {

using vf::Collection;
using vf::LoadOptions;
using vf::Neighbor;

const std::filesystem::path kGoldenDir = std::filesystem::path(VF_TEST_DATA_DIR) / "golden";

const LoadOptions kModes[] = {
    {.use_mmap = false}, {.use_mmap = true}, {.use_mmap = true, .verify = vf::Verify::Full}};

// Same formula as integer_vector() in tools/make_golden.py.
std::vector<float> integer_vector(int i, int dim) {
  std::vector<float> v(static_cast<std::size_t>(dim));
  for (int j = 0; j < dim; ++j) {
    v[static_cast<std::size_t>(j)] = static_cast<float>((((i * 7) + (j * 3) + (i * j)) % 11) - 5);
  }
  return v;
}

std::vector<float> normalized(const std::vector<float>& v) {
  double norm = 0;
  for (const float x : v) {
    norm += static_cast<double>(x) * static_cast<double>(x);
  }
  norm = std::sqrt(norm);
  std::vector<float> out;
  for (const float x : v) {
    out.push_back(static_cast<float>(static_cast<double>(x) / norm));
  }
  return out;
}

std::vector<Neighbor> search(const Collection& c, const std::vector<float>& q, std::uint32_t k,
                             std::uint32_t ef) {
  vf::SearchParams p;
  p.k = k;
  if (ef != 0) {
    p.ef_search = ef;
  }
  return c.search(q, p).value();
}

void expect_resaves_identically(const Collection& c, const std::filesystem::path& golden) {
  EXPECT_EQ(vf::test::save_to_memory(c), vf::test::read_bytes(golden))
      << "C++ writer output differs from " << golden.filename().string();
}

TEST(GoldenFiles, FlatL2) {
  const std::filesystem::path file = kGoldenDir / "v1.0_flat_l2.vfidx";
  for (const LoadOptions& mode : kModes) {
    const auto loaded = Collection::load(file, mode);
    ASSERT_TRUE(loaded.ok()) << loaded.status().to_string();
    const Collection& c = *loaded.value();
    EXPECT_EQ(c.config().dim, 4U);
    EXPECT_EQ(c.config().metric, vf::Metric::L2);
    EXPECT_EQ(c.config().index, vf::IndexType::Flat);
    EXPECT_EQ(c.size(), 12U);
    EXPECT_EQ(c.stats().deleted_count, 0U);
    std::vector<vf::test::RefItem> items;
    std::vector<std::vector<float>> rows;
    for (int i = 0; i < 12; ++i) {
      rows.push_back(integer_vector(i, 4));
    }
    for (int i = 0; i < 12; ++i) {
      const vf::ExternalId id = 100 + (3 * static_cast<vf::ExternalId>(i));
      ASSERT_EQ(c.get(id).value(), rows[static_cast<std::size_t>(i)]) << "id " << id;
      items.push_back({id, static_cast<std::uint64_t>(i), rows[static_cast<std::size_t>(i)]});
    }
    for (int qi = 0; qi < 20; ++qi) {
      const std::vector<float> q = integer_vector(qi * 5 + 1, 4);
      vf::test::expect_exact_topk(search(c, q, 5, 0),
                                  vf::test::reference_ranking(vf::Metric::L2, false, q, items), 5);
    }
    expect_resaves_identically(c, file);
  }
}

TEST(GoldenFiles, HnswCosineWithTombstones) {
  const std::filesystem::path file = kGoldenDir / "v1.0_hnsw_cosine.vfidx";
  for (const LoadOptions& mode : kModes) {
    const auto loaded = Collection::load(file, mode);
    ASSERT_TRUE(loaded.ok()) << loaded.status().to_string();
    const Collection& c = *loaded.value();
    EXPECT_EQ(c.config().dim, 3U);
    EXPECT_EQ(c.config().metric, vf::Metric::Cosine);
    EXPECT_EQ(c.config().hnsw.M, 2U);
    EXPECT_EQ(c.config().hnsw.ef_construction, 8U);
    EXPECT_EQ(c.config().hnsw.ef_search, 16U);
    EXPECT_EQ(c.config().hnsw.max_level, 4U);
    EXPECT_EQ(c.config().hnsw.seed, 12345U);
    EXPECT_EQ(c.size(), 14U);
    EXPECT_EQ(c.stats().deleted_count, 2U);
    EXPECT_FALSE(c.contains(5003));
    EXPECT_FALSE(c.contains(5010));

    const auto& backend = static_cast<const vf::detail::HnswBackend&>(
        *vf::detail::CollectionFactory::state(c).backend);
    const vf::detail::HnswGraph& graph = backend.graph();
    EXPECT_EQ(graph.entry().id, 0U);
    EXPECT_EQ(graph.entry().level, 2U);
    EXPECT_EQ(graph.level(5), 1U);
    ASSERT_EQ(graph.links(0, 0).size(), 2U);
    EXPECT_EQ(graph.links(0, 0)[0], 1U);
    EXPECT_EQ(graph.links(0, 0)[1], 15U);
    const vf::detail::HnswValidator validator(graph);
    EXPECT_TRUE(validator.check_invariants().ok());
    EXPECT_EQ(validator.reachability().unreachable_level0(), 0U);

    std::vector<std::vector<float>> raw;
    std::vector<vf::test::RefItem> items;
    for (int i = 0; i < 16; ++i) {
      raw.push_back(integer_vector(i + 1, 3));
    }
    for (int i = 0; i < 16; ++i) {
      const vf::ExternalId id = 5000 + static_cast<vf::ExternalId>(i);
      if (i == 3 || i == 10) {
        continue;
      }
      ASSERT_EQ(c.get(id).value(), normalized(raw[static_cast<std::size_t>(i)])) << "id " << id;
      items.push_back({id, static_cast<std::uint64_t>(i), raw[static_cast<std::size_t>(i)]});
    }
    // ef >= live count explores the whole (connected) graph, so results are exact.
    for (int qi = 0; qi < 20; ++qi) {
      const std::vector<float> q = integer_vector((qi * 3) + 2, 3);
      if (std::all_of(q.begin(), q.end(), [](float x) { return x == 0.0F; })) {
        continue;
      }
      vf::test::expect_tolerant_topk(
          search(c, q, 4, 16), vf::test::reference_ranking(vf::Metric::Cosine, true, q, items), 4,
          1e-5);
    }
    expect_resaves_identically(c, file);
  }
}

TEST(GoldenFiles, EmptyHnswInnerProduct) {
  const std::filesystem::path file = kGoldenDir / "v1.0_hnsw_ip_empty.vfidx";
  for (const LoadOptions& mode : kModes) {
    const auto loaded = Collection::load(file, mode);
    ASSERT_TRUE(loaded.ok()) << loaded.status().to_string();
    const Collection& c = *loaded.value();
    EXPECT_EQ(c.config().dim, 7U);
    EXPECT_EQ(c.config().metric, vf::Metric::InnerProduct);
    EXPECT_EQ(c.config().hnsw.M, 4U);
    EXPECT_EQ(c.size(), 0U);
    EXPECT_TRUE(search(c, std::vector<float>(7, 1.0F), 3, 0).empty());
    expect_resaves_identically(c, file);
  }
}

TEST(GoldenFiles, ReportsSimdSelectionError) {
  // Run by CTest with an invalid VF_SIMD (simd.load_reports_invalid_request) and in normal runs.
  const vf::Status simd = vf::simd_status();
  for (const LoadOptions& mode : kModes) {
    const auto loaded = Collection::load(kGoldenDir / "v1.0_flat_l2.vfidx", mode);
    if (simd.ok()) {
      EXPECT_TRUE(loaded.ok()) << loaded.status().to_string();
    } else {
      ASSERT_FALSE(loaded.ok());
      EXPECT_EQ(loaded.status().code(), simd.code());
    }
  }
}

TEST(GoldenFiles, InsertAfterLoad) {
  // Phase 3 edge case deferred to Phase 4: a loaded HNSW graph accepts inserts and stays valid.
  const auto loaded = Collection::load(kGoldenDir / "v1.0_hnsw_cosine.vfidx").value();
  vf::test::apply_operations(*loaded, 9, 200, 0);
  const auto& backend = static_cast<const vf::detail::HnswBackend&>(
      *vf::detail::CollectionFactory::state(*loaded).backend);
  EXPECT_TRUE(vf::detail::HnswValidator(backend.graph()).check_invariants().ok());
  EXPECT_EQ(loaded->search(std::vector<float>{1, 2, 3}).value().size(), 10U);
}

}  // namespace
